### ISSUE TITLE
missing function

### ISSUE THREAD

**Issue by nicolasStevenin** [cespare/xxhash#10]
Hello,
When I try to test the cmd/influxd/run in the project github.com/influxdata/influxdb in version 1.4.2 it fails with

# github.com/cespare/xxhash
/usr/share/gocode/src/github.com/cespare/xxhash/xxhash_amd64.go:10: missing function body for "Sum64"
/usr/share/gocode/src/github.com/cespare/xxhash/xxhash_amd64.go:12: missing function body for "writeBlocks"

Thank you for your help

**Comment by cespare** [comment]
How did you download this package? What files do you see in `/usr/share/gocode/src/github.com/cespare/xxhash/`? It sounds like you're missing a .s file.

**Comment by nicolasStevenin** [comment]
Yes ! In fact I forgot to install your .s file, i only installed the go files
Thanks
