### ISSUE TITLE
Release xxhash v2

### ISSUE THREAD

**Issue by cespare** [cespare/xxhash#17]
We'll have a minor backwards incompatibility so we should bump the major version.

**Comment by ongardie-ebay** [comment]
@cespare, do you plan to include any other changes in the v2 release?

**Comment by ongardie-ebay** [comment]
Oh, I see there's a v2 milestone.

**Comment by cespare** [comment]
Released.

**Comment by Dieterbe** [comment]
> We'll have a minor backwards incompatibility so we should bump the major version.

as an outsider, this is pretty hard to figure out. https://github.com/cespare/xxhash/releases doesn't have a changelog
i did some spelunking and found https://github.com/cespare/xxhash/issues/13#issuecomment-442296125 ; is it correct to say that the only breaking change is the rename of the type?

**Comment by cespare** [comment]
It's not the renaming of the type that's backward-incompatible (since the old name, `xxh`, wasn't exported anyway). It's just the fact that `New` changed its signature from `New() hash.Hash64` to `New() *Digest`.
