### ISSUE TITLE
can do a xxh3 or v3?

### ISSUE THREAD

**Issue by hiqsociety** [cespare/xxhash#27]
can do a xxh3 or v3?

with reference to this
https://github.com/dgryski/go-xxh3

would like to standardize the calling function so we can just call the function by changing the github import location

**Comment by cespare** [comment]
If I understand your request correctly, I'd prefer not to add a dependency just to add a wrapper for that code in this project. I also don't have immediate plans to implement xxh3 myself. But I imagine that making the wrapper yourself is straightforward.
