### ISSUE TITLE
v2 module indirectly imports v1 module

### ISSUE THREAD

**Issue by mpx** [cespare/xxhash#28]
github.com/cespare/xxhash/v2 currently requires the github.com/cespare/xxhash (v1) module:

```
$ go mod why github.com/cespare/xxhash
# github.com/cespare/xxhash
example/import
github.com/cespare/xxhash/v2
github.com/cespare/xxhash/v2.test
github.com/OneOfOne/xxhash
github.com/OneOfOne/xxhash.test
github.com/cespare/xxhash
```

A later version of github.com/OneOfOne/xxhash (v1.2.5) has moved their benchmarks to a separate sub-module which prevents the indirect import of github.com/cespare/xxhash.

Please update your github.com/OneOfOne/xxhash dependency -- this will remove the unnecessary github.com/cespare/xxhash module reference.

Also, please consider moving your benchmarks to a sub-module since most users of your module won't be interested in the alternate modules used for benchmarking.

**Comment by cespare** [comment]
Good suggestions. I'll make the changes shortly.

**Comment by cespare** [comment]
v2.1.0 has the fix (no dependencies now).

**Comment by mpx** [comment]
Thanks for the quick fix! Works well.
