### ISSUE TITLE
cespare/xxhash/v2 was deleted

### ISSUE THREAD

**Issue by udayangaac** [cespare/xxhash#30]
@cespare we faced such error when building our project using glide `[ERROR] Error scanning github.com/cespare/xxhash/v2: cannot find package "." in:
        /home/chamith/.glide/cache/src/https-github.com-cespare-xxhash/v2
`

**Comment by cespare** [comment]
I haven't changed anything. This sounds like a problem you're having with Glide.

**Comment by udayangaac** [comment]
Thank you

**Comment by cespare** [comment]
As I mentioned in #31, you need a version of Go with module support (1.11+) to use v2 of this module.

**Comment by ArtemChekunov** [comment]
`GO111MODULE=on go mod vendor` is solved the problem for me
