### ISSUE TITLE
missing v2 visibility

### ISSUE THREAD

**Issue by wfbrown53** [cespare/xxhash#31]
Trying to build a govendor package and the github.com/prometheus/client_golang references a xxhash/v2, specically github.com/cespare/xxhash/v2 v2.1.0. Is that version available for build purposes?

**Comment by wfbrown53** [comment]
ok. Try fetching and building github.com/carlpett/stream_exporter with govendor. Sorry that I would think my issue was complete enough.

**Comment by cespare** [comment]
FWIW if I clone https://github.com/carlpett/stream_exporter I can run `govendor build  +p` and it works.

**Comment by wfbrown53** [comment]
Go figure. It must be something in my win10 env. Here is some runs.
C:\Users\bro\go\src>govendor -version
v1.0.9

C:\Users\bro\go\src>govendor init

C:\Users\bro\go\src>govendor fetch github.com/carlpett/stream_exporter

C:\Users\bro\go\src>govendor build +p

C:\Users\bro\go\src>

Deleted everything under src and retried

C:\Users\bro\go\src>govendor init

C:\Users\bro\go\src>govendor fetch github.com/carlpett/stream_exporter

C:\Users\bro\go\src>
C:\Users\bro\go\src>govendor build +p
vendor\github.com\prometheus\client_golang\prometheus\desc.go:22:2: cannot find package "github.com/cespare/xxhash/v2" in any of:
        C:\Users\bro\go\src\vendor\github.com\cespare\xxhash\v2 (vendor tree)
        c:\go\src\github.com\cespare\xxhash\v2 (from $GOROOT)
        C:\Users\bro\go\src\github.com\cespare\xxhash\v2 (from $GOPATH)
Error: exit status 1

C:\Users\bro\go\src>

**Comment by iricigor** [comment]
I have the same issue...

**Comment by fredsted** [comment]
Same issue here.

**Comment by kkalin78** [comment]
I got same issue and debugged a bit. I narrowed down it to Golang 1.10.2. Upgrading Golang version to 1.10.8 solved the issue. I didn't try more recent Golang versions. Hope it gives some ideas about a source of the issue.

**Comment by bryceyang** [comment]
same here with govendor. Does anyone find anything could help us out?

**Comment by cespare** [comment]
You definitely need a version of Go with module support (1.11+) to use v2 of this module.

I added a note to the README in 997e1685cae39ce5a9573990e7fabe3e796898a0.

**Comment by ArtemChekunov** [comment]
`GO111MODULE=on go mod vendor` is solved the problem for me
