### ISSUE TITLE
collision likeness?

### ISSUE THREAD

**Issue by pkieltyka** [cespare/xxhash#59]
thanks for this awesome library. I'm thinking of using xxhash/v2 to generate primary key based on contents of data, however I was wondering about the likelyhood of collisions assume a large input (ie. 40+ bytes)? thanks for any insights you can provide

**Comment by cespare** [comment]
You can read about this on this on the [xxhash wiki](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison) and elsewhere.

**Comment by shenwei356** [comment]
I found one, using `xxhash.Sum64()`, tested in v2.1.2 and v2.3.0.

Input 1: `a00725:175:hk7lydsxf:1:1533:10719:6433 1:n:0:cgctagta+ctgatgag`
Hash 1: 14819594535917712234

Input 2: `a00725:175:hk7lydsxf:3:2443:32606:14622 1:n:0:cgctagta+ctgatgag`
Hash 2: 14819594535917712234

**Comment by cespare** [comment]
Forcing a collision in a non-cryptographic hash function isn't difficult. Even just finding a random birthday collision is feasible with a 64-bit hash function.
