### ISSUE TITLE
Please documents which xxhash version is used

### ISSUE THREAD

**Issue by hitzhangjie** [cespare/xxhash#67]
As README references several common hash functions, xxh3 etc. 

It's likely to misunderstand that this repo is xxh3.
Actually it's not. Please documents the xxhash version.
Maybe many people couldn't determine the version from the code.

I see that from the closed issues.

**Comment by cespare** [comment]
> As README references several common hash functions, xxh3 etc.

The readme does not mention xxh3.

> It's likely to misunderstand that this repo is xxh3.
> Actually it's not. Please documents the xxhash version.

It's right there in the very first sentence of the README:

> xxhash is a Go implementation of the 64-bit [xxHash](http://cyan4973.github.io/xxHash/) algorithm, XXH64.
