### ISSUE TITLE
 can't find reason for requirement

### ISSUE THREAD

**Issue by DouFuJuShi** [cespare/xxhash#69]
panic:  internal error: can't find reason for requirement on github.com/cespare/xxhash/v2@v2.1.2

**Comment by cespare** [comment]
This is a Go issue, not an xxhash one. See https://github.com/golang/go/issues/47979 and https://github.com/golang/go/issues/56494. There are some workarounds listed there.

**Comment by DouFuJuShi** [comment]
TKS
