### ISSUE TITLE
Add XXH3_64bits and XXH3_128bits

### ISSUE THREAD

**Issue by metalim** [cespare/xxhash#73]
Subj

Mainly need 128bit hash on aarch64, looking for XXH3 128 bit Go implementation

**Comment by cespare** [comment]
I have no current plans to implement this. I recommend taking a look at other existing implementations such as [github.com/zeebo/xxh3](https://pkg.go.dev/github.com/zeebo/xxh3) (though I haven't used it myself and I don't know how it performance on arm64).
