### ISSUE TITLE
Question about `digest.WriteString`

### ISSUE THREAD

**Issue by miparnisari** [cespare/xxhash#82]
https://github.com/cespare/xxhash/blob/ab37246c889f9db16b606fda1c232d659df9271d/xxhash_unsafe.go#L43-L45

I'm curious about the 
> It always returns len(s), nil.

comment. Why have `error` as a return value at all?

**Comment by cespare** [comment]
So that Digest implements the standard [StringWriter](https://pkg.go.dev/io#StringWriter) interface.

**Comment by miparnisari** [comment]
Ah, that was what I imagined. Thank you!
